# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roster_side',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='None', max_length=5),
        ),
    ]
