# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtr_start_date', models.DateField(blank=True, null=True)),
                ('qtr_end_date', models.DateField(blank=True, null=True)),
                ('qtr_label', models.CharField(max_length=5)),
            ],
        ),
    ]
