# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-17 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clocking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_shift_label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='None', max_length=2)),
                ('roster_shift_date', models.DateField()),
                ('roster_due_on', models.BooleanField()),
                ('roster_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RosterSideA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ros_a_shift_cycle_number', models.IntegerField()),
                ('ros_a_shift_label', models.CharField(blank=True, max_length=3, null=True)),
                ('ros_a_due_on', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RosterSideB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ros_b_shift_cycle_number', models.IntegerField()),
                ('ros_b_shift_label', models.CharField(blank=True, max_length=3, null=True)),
                ('ros_b_due_on', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('shift_duration', models.FloatField(default=11.0)),
            ],
        ),
        migrations.AddField(
            model_name='roster',
            name='roster_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_shift', to='clocking.Shift'),
        ),
    ]
