# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-18 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clocking', '0003_auto_20201118_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('eircode', models.CharField(max_length=10)),
                ('county', models.CharField(choices=[('Carlow', 'Carlow'), ('Cork', 'Cork'), ('Dublin', 'Dublin'), ('Kildare', 'Kildare'), ('Laois', 'Laois'), ('Limerick', 'Limerick'), ('Louth', 'Louth'), ('Meath', 'Meath'), ('Offaly', 'Offaly'), ('Wicklow', 'Wicklow')], default='None', max_length=15)),
                ('contact_number', models.CharField(max_length=12)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact', models.CharField(max_length=50)),
                ('relationship_to_emergency_contact', models.CharField(max_length=30)),
                ('emergency_contact_number', models.CharField(max_length=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('officer_pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_pd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
