# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-23 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clocking', '0004_personaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualClocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocking_date', models.DateField()),
                ('clocking_in_time', models.TimeField()),
                ('clocking_out_time', models.TimeField()),
                ('lunch_out_time', models.TimeField()),
                ('lunch_in_time', models.TimeField()),
                ('reason_for_missed_clocking', models.CharField(max_length=200)),
                ('checked_by_validator', models.BooleanField(default=False)),
                ('accept_reject_clock', models.BooleanField(default=False)),
                ('reason_manual_clock_rejected', models.TextField(blank=True, max_length=400, null=True)),
                ('mc_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_officer_id', to=settings.AUTH_USER_MODEL)),
                ('validator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validator_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='roster',
            name='clocking_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='clocking_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='lunch_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='lunch_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='number_of_clockings',
            field=models.IntegerField(default=0),
        ),
    ]
