# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-21 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clocking', '0005_auto_20201123_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_late', models.DateField()),
                ('late_clocking_time', models.TimeField()),
                ('duration_of_late', models.DurationField()),
                ('lates_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lates_officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LatesPerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lates_year', models.IntegerField()),
                ('number_lates_for_year', models.IntegerField()),
                ('yearly_lates_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_lates_officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
