# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-30 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clocking', '0006_lates_latesperyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteClock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_number_of_clockings', models.IntegerField(default=0)),
                ('remote_clock_in_address', models.CharField(blank=True, max_length=2000, null=True)),
                ('remote_clock_in_latitude', models.FloatField(blank=True, null=True)),
                ('remote_clock_in_longitude', models.FloatField(blank=True, null=True)),
                ('remote_clocking_in_time', models.TimeField(blank=True, null=True)),
                ('remote_lunch_out_address', models.CharField(blank=True, max_length=2000, null=True)),
                ('remote_lunch_out_latitude', models.FloatField(blank=True, null=True)),
                ('remote_lunch_out_longitude', models.FloatField(blank=True, null=True)),
                ('remote_lunch_out_time', models.TimeField(blank=True, null=True)),
                ('remote_lunch_in_address', models.CharField(blank=True, max_length=2000, null=True)),
                ('remote_lunch_in_latitude', models.FloatField(blank=True, null=True)),
                ('remote_lunch_in_longitude', models.FloatField(blank=True, null=True)),
                ('remote_lunch_in_time', models.TimeField(blank=True, null=True)),
                ('remote_clock_out_address', models.CharField(blank=True, max_length=2000, null=True)),
                ('remote_clock_out_latitude', models.FloatField(blank=True, null=True)),
                ('remote_clock_out_longitude', models.FloatField(blank=True, null=True)),
                ('remote_clocking_out_time', models.TimeField(blank=True, null=True)),
                ('remote_clocking_date', models.DateField(blank=True, null=True)),
                ('remote_clock_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_clock_officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
