# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-10 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='swap_started_from_noticeboard',
            field=models.BooleanField(default=False),
        ),
    ]
