# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clocking', '0005_auto_20201123_1901'),
        ('exchanges', '0002_exchangerequest_swap_started_from_noticeboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='exchanging_req_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchanging_req_shift', to='clocking.Shift'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='replacing_req_shift_label',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='replacing_req_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacing_req_shift', to='clocking.Shift'),
        ),
    ]
