# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-20 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clocking', '0004_personaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowancesRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_req_task', models.CharField(max_length=600)),
                ('allow_req_date', models.DateField()),
                ('claiming_breakfast_allowance', models.BooleanField(default=False)),
                ('claiming_dinner_allowance', models.BooleanField(default=False)),
                ('claiming_tea_allowance', models.BooleanField(default=False)),
                ('claiming_plain_clothes_allowance', models.BooleanField(default=False)),
                ('claiming_food_for_prisoner_expense', models.BooleanField(default=False)),
                ('food_for_prisoner_amount', models.FloatField(blank=True, null=True)),
                ('receipt_for_prisoner_food', models.ImageField(blank=True, null=True, upload_to='food_receipts_images')),
                ('claim_total', models.FloatField(blank=True, null=True)),
                ('allow_req_date_submitted', models.DateField(auto_now_add=True)),
                ('allow_req_checked_by_validator', models.BooleanField(default=False)),
                ('allow_req_accepted', models.BooleanField(default=False)),
                ('reason_allowance_req_rejected', models.CharField(blank=True, max_length=600, null=True)),
                ('allow_req_off_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allow_req_off_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_one', models.DateField()),
                ('mon_two', models.DateField()),
                ('tue_one', models.DateField()),
                ('tue_two', models.DateField()),
                ('wed_one', models.DateField()),
                ('wed_two', models.DateField()),
                ('thurs_one', models.DateField()),
                ('thurs_two', models.DateField()),
                ('fri_one', models.DateField()),
                ('fri_two', models.DateField()),
                ('sat_one', models.DateField()),
                ('sat_two', models.DateField()),
                ('sun_one', models.DateField()),
                ('sun_two', models.DateField()),
                ('avail_sheet_date_submitted', models.DateField(auto_now_add=True)),
                ('avail_sheet_off_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail_sheet_off_id', to=settings.AUTH_USER_MODEL)),
                ('avail_sheet_qtr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail_sheet_qtr_id', to='clocking.Quarter')),
            ],
        ),
        migrations.CreateModel(
            name='NonScheduledOvertimeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsot_date', models.DateField()),
                ('nsot_start_time', models.TimeField()),
                ('nsot_end_time', models.TimeField()),
                ('ot_hours_claimed', models.FloatField(blank=True, null=True)),
                ('nsot_task', models.CharField(max_length=600)),
                ('directed_by', models.CharField(max_length=600)),
                ('nsot_date_submitted', models.DateField(auto_now_add=True)),
                ('nsot_checked_by_validator', models.BooleanField(default=False)),
                ('nsot_accepted', models.BooleanField(default=False)),
                ('reason_nsot_rejected', models.CharField(blank=True, max_length=600, null=True)),
                ('nsot_off_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nsot_off_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_date', models.DateField(blank=True, null=True)),
                ('ot_recall', models.BooleanField(default=False)),
                ('ot_requirement', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ot_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_officer_id', to=settings.AUTH_USER_MODEL)),
                ('ot_qtr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_qtr_id', to='clocking.Quarter')),
                ('ot_shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_shift_id', to='clocking.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimePerQtr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_hours_completed', models.FloatField(default=0.0)),
                ('avail_window_open', models.BooleanField(default=False)),
                ('ot_per_qtr_off_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_per_qtr_off_id', to=settings.AUTH_USER_MODEL)),
                ('ot_per_qtr_qtr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_per_qtr_qtr_id', to='clocking.Quarter')),
            ],
        ),
        migrations.CreateModel(
            name='ShortOvertime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_ot_date', models.DateField()),
                ('short_ot_start_time', models.TimeField()),
                ('short_ot_end_time', models.TimeField()),
                ('overtime_hours', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('short_ot_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_ot_officer_id', to=settings.AUTH_USER_MODEL)),
                ('short_ot_qtr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_ot_qtr_id', to='clocking.Quarter')),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermAvailabilty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_availability_date', models.DateField()),
                ('st_availability_off_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_availability_off_id', to=settings.AUTH_USER_MODEL)),
                ('st_availability_qtr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_availability_qtr_id', to='clocking.Quarter')),
            ],
        ),
    ]
