# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-18 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('al_date', models.DateField(blank=True, null=True)),
                ('leave_amount_used', models.IntegerField()),
                ('short_term_leave', models.BooleanField(default=False)),
                ('al_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='al_officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnualLeaveCarriedOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('leave_amount_carried_over', models.IntegerField()),
                ('al_carried_over_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='al_carried_over_officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnualLeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_request_start_date', models.DateField(blank=True, null=True)),
                ('leave_request_last_date', models.DateField(blank=True, null=True)),
                ('leave_request_checked_by_validator', models.BooleanField(default=False)),
                ('leave_request_granted', models.BooleanField(default=False)),
                ('reason_leave_rejected', models.CharField(blank=True, max_length=400, null=True)),
                ('al_request_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='al_request_officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermAnnualLeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_leave_date', models.DateField(blank=True, null=True)),
                ('st_leave_start_time', models.TimeField()),
                ('st_leave_finish_time', models.TimeField()),
                ('st_leave_amount', models.FloatField(blank=True, null=True)),
                ('st_leave_request_checked_by_validator', models.BooleanField(default=False)),
                ('st_leave_request_granted', models.BooleanField(default=False)),
                ('reason_st_leave_rejected', models.CharField(blank=True, max_length=400, null=True)),
                ('st_annual_leave_request_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_annual_leave_request_officer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
